baseURL = 'https://lvfeir0.github.io/'
languageCode = 'en-us'
title = "taki's blog"
theme = 'PaperMod'
publishDir = 'docs'
enableEmoji = 'true'


[params.homeInfoParams]
Title = "1111111111111"
Content = "welcome to my blog"

[[menu.main]]
name = "All"
url = "archives/"
weight = 5
